/**
 * Where the mascot's pieces sit on the master canvas.
 *
 * Generated by tools/build_mascot_assets.py from the pack's
 * source/rig/HAICI_Mascot_Rig.json -- do not edit by hand.
 */
export const MASCOT_RIG = {
  /** Canvas every layer is registered against, in mascot units. */
  master: { width: 2000, height: 3200 },
  /** Top-left and side of the square canvas the face overlays use. */
  faceOverlay: { x: 488, y: 290, size: 1024 },
  /** Rotation centres, in master units. */
  pivots: {
    neck: { x: 1000, y: 1325 },
    antenna: { x: 1000, y: 215 },
  },
} as const;
